import { getMarketRegimePrediction } from "../services/mlService.js";

/**
 * Handles GET /api/ml/prediction
 * Protected endpoint returning the latest market context regime prediction
 * generated by the Python ML layer.
 */
export const getMlPrediction = async (req, res) => {
  try {
    const prediction = await getMarketRegimePrediction();

    if (!prediction || !prediction.available) {
      return res.status(200).json({
        success: true,
        available: false,
        reason: prediction?.reason || "ML prediction service is currently unavailable",
        isLive: false,
        generatedAt: new Date().toISOString(),
      });
    }

    res.status(200).json({
      success: true,
      available: true,
      model: prediction.model,
      predictedRegime: prediction.predictedRegime,
      regimeName: prediction.regimeName,
      probabilities: prediction.probabilities,
      dataSource: prediction.dataSource,
      benchmarkDate: prediction.benchmarkDate,
      isLive: false,
      generatedAt: prediction.generatedAt,
      notice: "Historical benchmark signal for educational decision support; does not constitute personalized financial advice.",
    });
  } catch (error) {
    console.error("ML prediction endpoint error:", error);
    res.status(500).json({
      success: false,
      available: false,
      message: "Failed to generate market context prediction",
    });
  }
};
