import Sidebar from "../components/Sidebar";

import {
  BrainCircuit,
  Info
} from "lucide-react";

function XAI() {
  return (
    <div className="dashboard-layout">

      <Sidebar />

      <main className="dashboard-main">

        <div className="dashboard-header">

          <div>
            <span className="page-label">
              EXPLAINABLE AI
            </span>

            <h1>Why was this recommended?</h1>

            <p>
              Understand the factors that influenced the recommendation.
            </p>
          </div>

        </div>


        <div className="xai-main-card">

          <div className="xai-title">

            <BrainCircuit size={28} />

            <div>
              <span>RECOMMENDED INVESTMENT</span>

              <h2>
                Large Cap Equity
              </h2>
            </div>

          </div>


          <div className="xai-score">

            <strong>91%</strong>

            <span>
              Suitability Score
            </span>

          </div>


          <div className="factor-list">

            <div className="factor">

              <div>
                <span>Investment Horizon</span>
                <p>
                  Your long-term horizon supports equity exposure.
                </p>
              </div>

              <strong>+26%</strong>

            </div>


            <div className="factor">

              <div>
                <span>Risk Tolerance</span>
                <p>
                  Your moderate risk profile matches this category.
                </p>
              </div>

              <strong>+23%</strong>

            </div>


            <div className="factor">

              <div>
                <span>Financial Goal</span>
                <p>
                  Your wealth-creation goal supports growth-oriented assets.
                </p>
              </div>

              <strong>+19%</strong>

            </div>


            <div className="factor">

              <div>
                <span>Investment Experience</span>
                <p>
                  Your experience level is compatible with this category.
                </p>
              </div>

              <strong>+12%</strong>

            </div>

          </div>


          <div className="xai-info">

            <Info size={18} />

            <p>
              In the final system, these feature contributions will
              be generated by the machine-learning model using an
              explainability technique such as SHAP.
            </p>

          </div>

        </div>

      </main>

    </div>
  );
}

export default XAI;